language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

install:
 - pip install .
 - pip install coveralls coverage
 - pip install PyVirtualDisplay
 - pip install six

script:  
 - cd tests && nosetests -v --with-coverage --cover-package=easyprocess  .
 
after_success:
 - coveralls
