language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

install:
 - pip install coveralls coverage
 - pip install PyVirtualDisplay
 - pip install six

script:  
 - python setup.py nosetests --with-coverage --cover-package=easyprocess  -w `pwd`/tests
 
after_success:
 - coveralls
