language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y iputils-ping

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
script:  
 - python setup.py nosetests --with-coverage --cover-package=easyprocess  -w `pwd`/tests
 
after_success:
 - coveralls
